# Generated by Django 3.1.5 on 2021-01-26 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50)),
                ('car_model', models.CharField(max_length=100)),
                ('car_assigned_number', models.IntegerField()),
                ('car_plate_number', models.CharField(max_length=20)),
                ('car_going_from', models.CharField(max_length=50)),
                ('car_going_to', models.CharField(max_length=50)),
                ('car_assigned_driver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=12)),
                ('travelling_from', models.CharField(max_length=50)),
                ('travelling_to', models.CharField(max_length=50)),
                ('next_of_kin_name', models.CharField(max_length=100)),
                ('next_of_kin_number', models.CharField(max_length=12)),
                ('travel_date', models.DateField()),
                ('amount_paid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departing_from', models.CharField(max_length=50)),
                ('departing_to', models.CharField(max_length=50)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('car_assigned', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bookings.car')),
            ],
        ),
    ]
