# Generated by Django 3.1.5 on 2021-01-26 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_car_car_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='assigned_car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='bookings.car'),
            preserve_default=False,
        ),
    ]
